// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA02ekk3pEogq__ROl0AddOrQKoztCaHlc',
    appId: '1:788095359359:web:e53fb3d8deef3b630c224a',
    messagingSenderId: '788095359359',
    projectId: 'medi-90cb0',
    authDomain: 'medi-90cb0.firebaseapp.com',
    storageBucket: 'medi-90cb0.appspot.com',
    measurementId: 'G-HVXKTBWY8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCpPoJ9CgLkMwJ6fw52awk9vqRSXOApns',
    appId: '1:788095359359:android:d62693be683078e80c224a',
    messagingSenderId: '788095359359',
    projectId: 'medi-90cb0',
    storageBucket: 'medi-90cb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvVes423KF-rsqbCZMdWqevxycbnjXGn8',
    appId: '1:788095359359:ios:e107459d3968cf100c224a',
    messagingSenderId: '788095359359',
    projectId: 'medi-90cb0',
    storageBucket: 'medi-90cb0.appspot.com',
    iosBundleId: 'com.example.helloDoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvVes423KF-rsqbCZMdWqevxycbnjXGn8',
    appId: '1:788095359359:ios:e107459d3968cf100c224a',
    messagingSenderId: '788095359359',
    projectId: 'medi-90cb0',
    storageBucket: 'medi-90cb0.appspot.com',
    iosBundleId: 'com.example.helloDoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA02ekk3pEogq__ROl0AddOrQKoztCaHlc',
    appId: '1:788095359359:web:91a69c1a4e7b26680c224a',
    messagingSenderId: '788095359359',
    projectId: 'medi-90cb0',
    authDomain: 'medi-90cb0.firebaseapp.com',
    storageBucket: 'medi-90cb0.appspot.com',
    measurementId: 'G-Z85CSPDQNV',
  );
}
